package com.example.signaling.enums;

public enum SignalType {
    RINGING, READY, JOINED, CREATED, ANSWER, 
    CONNECTED, DISCONNECTED,
    SEND_MESSAGE, GET_MESSAGE,
    SET_CALLER, ON_CALL, END_CALL, 
    JOIN_ROOM, WAIT_ROOM, LEAVE_ROOM, FULL_ROOM
}
